# Generated by Django 4.2.26 on 2025-11-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='source_file',
            field=models.FileField(blank=True, help_text='Upload raw video file here', null=True, upload_to='course_videos/raw/'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to the processed HLS stream', null=True),
        ),
    ]
