# Generated by Django 4.2.26 on 2025-11-26 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_videolesson_processing_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lms.lesson')),
                ('due_date', models.DateTimeField()),
                ('points', models.PositiveIntegerField(default=100)),
                ('file_submission_required', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Assignment',
            },
            bases=('lms.lesson',),
        ),
        migrations.CreateModel(
            name='LiveLesson',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lms.lesson')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('meeting_link', models.URLField(help_text='Zoom/Google Meet link')),
                ('recording_url', models.URLField(blank=True, help_text='Link to the recorded session', null=True)),
            ],
            options={
                'verbose_name': 'Live Lesson',
            },
            bases=('lms.lesson',),
        ),
        migrations.AddField(
            model_name='quizlesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='quizlesson',
            name='questions',
            field=models.JSONField(default=list, help_text='List of questions with options and correct answer'),
        ),
    ]
