# Generated by Django 4.2.26 on 2025-11-26 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_assignment_livelesson_quizlesson_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLesson',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lms.lesson')),
                ('file', models.FileField(help_text='PDF, Word (.doc, .docx) veya Excel (.xls, .xlsx) yükleyebilirsiniz', upload_to='course_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('file_type', models.CharField(blank=True, editable=False, max_length=10)),
                ('file_size', models.BigIntegerField(blank=True, editable=False, help_text='Dosya boyutu (bytes)', null=True)),
            ],
            options={
                'verbose_name': 'Document Lesson',
                'verbose_name_plural': 'Document Lessons',
            },
            bases=('lms.lesson',),
        ),
        migrations.DeleteModel(
            name='PDFLesson',
        ),
    ]
