# Generated by Django 4.2.26 on 2025-11-28 09:22

import apps.core.validators
import apps.lms.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_documentlesson_delete_pdflesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlesson',
            name='file',
            field=models.FileField(help_text='PDF, Word (.doc, .docx) veya Excel (.xls, .xlsx) yükleyebilirsiniz (Max: 5MB)', upload_to='course_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx']), apps.lms.models.DocumentLesson.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='source_file',
            field=models.FileField(blank=True, help_text='Upload raw video file (Max: 100MB, Formats: MP4, MOV, AVI, MKV, WEBM)', null=True, upload_to='course_videos/raw/', validators=[apps.core.validators.FileValidator.validate_video_file]),
        ),
    ]
